name: ML Pipeline Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Train the model
    - name: Train the model
      run: python train.py

    # Step 5: Evaluate the model
    - name: Evaluate the model
      run: python evaluate.py

    # Step 6: Save artifacts
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-model-and-metrics
        path: |
          model.pkl
          metrics.txt
