name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib pytest

  preprocessing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Run preprocessing
        run: python preprocessing.py


  training:
    runs-on: ubuntu-latest
    needs: preprocessing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Run model training
        run: python train_model.py


  testing:
    runs-on: ubuntu-latest
    needs: training
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Run tests
        run: pytest tests/
